const forms = require("@tailwindcss/forms");

module.exports = {
  darkMode: "class",
  content: ["./*.html", "./*.js"],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#303034",
        secondary: "#dfb7ff",
        "surface-container-lowest": "#0e0e12",
        "on-secondary-fixed": "#2d004f",
        outline: "#859397",
        "primary-fixed-dim": "#00daf7",
        "tertiary-fixed-dim": "#f8be28",
        "on-primary": "#00363e",
        "on-tertiary-fixed": "#261a00",
        "surface-variant": "#353439",
        "on-secondary-fixed-variant": "#6b00b0",
        "surface-bright": "#39393d",
        "on-primary-fixed-variant": "#004e5a",
        "on-error": "#690005",
        "outline-variant": "#3b494c",
        "on-tertiary": "#402d00",
        "on-tertiary-container": "#6f5200",
        "on-secondary-container": "#f7e6ff",
        error: "#ffb4ab",
        "primary-fixed": "#a3eeff",
        "secondary-fixed": "#f1daff",
        "tertiary-fixed": "#ffdf9e",
        background: "#050508",
        "surface-container-low": "#1b1b1f",
        "on-primary-fixed": "#001f25",
        "on-background": "#e5e1e7",
        "on-surface-variant": "#bac9cd",
        "on-tertiary-fixed-variant": "#5b4300",
        "surface-dim": "#131317",
        "surface-tint": "#00daf7",
        "surface-container": "#1f1f23",
        "error-container": "#93000a",
        "on-surface": "#e5e1e7",
        "surface-container-highest": "#353439",
        "secondary-fixed-dim": "#dfb7ff",
        "on-error-container": "#ffdad6",
        "on-secondary": "#4b007e",
        "surface-container-high": "#2a292e",
        "inverse-primary": "#006877",
        "secondary-container": "#9d05ff",
        "on-primary-container": "#00606e",
        "primary-container": "#00e1ff",
        surface: "#131317",
        "inverse-surface": "#e5e1e7",
        primary: "#bcf2ff",
        "tertiary-container": "#ffc42f",
        tertiary: "#ffe6b9",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Inter"],
        label: ["Space Grotesk"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [forms],
};
